#!/bin/bash
echo "Bash version ${BASH_VERSION}..."
TEMPLATE_DIR=~/Documents/references/aide/hieroglyphSphinxModeles/
DEFAULT_AUTHOR=`grep "^$USER:" /etc/passwd | awk -F: '{print $5}'`
#
## HOME
read -p "Where do you want to setup a sphinx+hieroglyph project? [.] " DIR
if [ "$DIR" == "" ]; then
    DIR="."
fi
mkdir -p "$DIR" || exit -1
#
## TITLE
while [ "$title" == "" ]; do
      read -p "What is the title of the document? " title
done
#
## AUTHOR
echo -n "Who is the author of the project? [$DEFAULT_AUTHOR] "
read author
if [ "author" == "" ]; then
    author="$DEFAULT_AUTHOR"
fi
#
## DO IT
cp -R "$TEMPLATE_DIR"/* "$DIR"
#
for f in Makefile source/conf.py source/index.rst
 do
    perl -pi -e "s/REPLACE_ME_title/$title/g" "$DIR/$f"
    perl -pi -e "s/REPLACE_ME_author/$author/g" "$DIR/$f"
 done
